AWSTemplateFormatVersion: '2010-09-09'
Description: Daily reading infrastructure
Transform: AWS::Serverless-2016-10-31
Parameters:
  pDomainNameRoot:
    Type: String
  pDomainNameEmail:
    Type: String
  pDomainNameApi:
    Type: String
  pEmailSubject:
    Type: String
  pHostedZoneId:
    Type: String
Resources:
  # API Gateway
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref pDomainNameApi
      DomainValidationOptions:
        - DomainName: !Ref pDomainNameApi
          HostedZoneId: !Ref pHostedZoneId
      ValidationMethod: DNS
  Domain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref pDomainNameApi
      EndpointConfiguration:
        Types:
          - REGIONAL
      RegionalCertificateArn: !Ref Certificate
  DomainRecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref pHostedZoneId
      Name: !Ref pDomainNameApi
      Type: A
      AliasTarget:
        HostedZoneId: !GetAtt Domain.RegionalHostedZoneId
        DNSName: !GetAtt Domain.RegionalDomainName
  # SES
  EmailConfiguration:
    Type: AWS::SES::ConfigurationSet
    Properties:
      DeliveryOptions:
        TlsPolicy: REQUIRE
      ReputationOptions:
        ReputationMetricsEnabled: true
      SendingOptions:
        SendingEnabled: true
      SuppressionOptions:
        SuppressedReasons:
          - BOUNCE
          - COMPLAINT
      VdmOptions:
        DashboardOptions:
          EngagementMetrics: ENABLED
        GuardianOptions:
          OptimizedSharedDelivery: ENABLED
  EmailIdentity:
    Type: AWS::SES::EmailIdentity
    Properties:
      ConfigurationSetAttributes:
        ConfigurationSetName: !Ref EmailConfiguration
      EmailIdentity: !Ref pDomainNameRoot
      MailFromAttributes:
        BehaviorOnMxFailure: USE_DEFAULT_VALUE
        MailFromDomain: !Ref pDomainNameEmail
  EmailTemplate:
    Type: AWS::SES::Template
    Properties:
      Template:
        SubjectPart: !Sub "${pEmailSubject} for {{date}}"
        HtmlPart: "<p>{{reading}}</p><br><p><a href='{{complete}}'>Click here when you've completed today's reading</a>.</p><p>To unsubscribe, click <a href='{{unsubscribe}}'>here</a>.<p>"
Outputs:
  outCertificateArn:
    Value: !Ref Certificate
  outEmailIdentity:
    Value: !Ref EmailIdentity
  outEmailTemplate:
    Value: !Ref EmailTemplate