openapi: 3.0.3
info:
  title: reading-api
  description: Reading application API endpoint
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

components:
  schemas:
    error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    uid:
      type: string
      # pattern: "^\w{8}-\w{4}-\w{4}-\w{4}-\w{12}$"
      # minLength: 36
      # maxLength: 36
    uids:
      type: array
      items:
        $ref: "#/components/schemas/uid"
    group:
      type: object
      properties:
        uid:
          $ref: "#/components/schemas/uid"
        description:
          type: string
          minLength: 2
        is_private:
          type: boolean
      required:
        - description
        - is_private
    groups:
      type: array
      items:
        $ref: "#/components/schemas/group"
    user:
      type: object
      properties:
        uid:
          $ref: "#/components/schemas/uid"
        description:
          type: string
          minLength: 2
        email:
          type: string
          minLength: 6
        group_ids:
          $ref: "#/components/schemas/uids"
        plan_ids:
          $ref: "#/components/schemas/uids"
      required:
        - description
        - email
        - group_ids
        - plan_ids
    users:
      type: array
      items:
        $ref: "#/components/schemas/user"
    plan:
      type: object
      properties:
        uid:
          $ref: "#/components/schemas/uid"
        description:
          type: string
          minLength: 2
        is_private:
          type: boolean
      required:
        - description
        - is_private
    plans:
      type: array
      items:
        $ref: "#/components/schemas/plan"
    reading:
      type: object
      properties:
        uid:
          $ref: "#/components/schemas/uid"
        description:
          type: string
          minLength: 2
        body:
          type: string
        plan_id:
          $ref: "#/components/schemas/uid"
        sent_date:
          type: string
        sent_count:
          type: integer
      required:
        - description
        - body
        - plan_id
        - sent_date
        - sent_count
    readings:
      type: array
      items:
        $ref: "#/components/schemas/reading"
  responses:
    error:
      description: internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"
          example:
            code: 500
            message: "internal server error"
    uid:
      description: ok
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/uid"
          example:
            uid: "7f42847e-db7c-4c16-b390-a1e7f4448919"
    group:
      description: ok
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/group"
          example:
            uid: "e5512fda-c5ec-4485-84ac-2592cd09a985"
            description: "example group"
            is_private: false
    groups:
      description: ok
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/groups"
    user:
      description: ok
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/user"
          example:
            uid: "432b5bcd-ce1f-48fa-b8f8-b78bc4716178"
            description: "example user"
            email: user@example.com
            group_ids: ["f179415c-c87d-4645-b44a-3f07034cd9a4"]
            plan_ids: ["3def7b08-d3f9-45d9-b183-dd19d3f11a0f"]
    users:
      description: ok
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/users"
    plan:
      description: ok
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/plan"
          example:
            uid: "dc35c5f4-5ef4-4399-b3bc-c0e4c5467e3e"
            description: "example plan"
            is_private: false
    plans:
      description: ok
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/plans"
    reading:
      description: ok
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/reading"
          example:
            uid: "226ce991-dfa2-45f0-bf9f-369ab39c9c79"
            description: "example reading"
            body: "example text"
            plan_id: "48b2f512-0a76-4bfc-90c8-7c9d7cf76205"
            sent_date: "2023-12-27T17:22:16.870919"
            sent_count: 1
    readings:
      description: ok
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/readings"

paths:
  /group:
    get:
      summary: group
      description: returns list of groups
      parameters:
        - in: query
          name: uid
          required: false
          schema:
            $ref: "#/components/schemas/uid"
      responses:
        200:
          $ref: "#/components/responses/groups"
        500:
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-amazon-apigateway-request-validator: param
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: AWS_PROXY
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FnGroup}/invocations"
    post:
      summary: group
      description: creates group
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/group"
      responses:
        200:
          $ref: "#/components/responses/uid"
        500:
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-amazon-apigateway-request-validator: body
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: AWS_PROXY
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FnGroup}/invocations"
    put:
      summary: group
      description: updates a group
      parameters:
        - in: query
          name: uid
          required: true
          schema:
            $ref: "#/components/schemas/uid"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/group"
      responses:
        200:
          $ref: "#/components/responses/group"
        500:
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-amazon-apigateway-request-validator: both
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: AWS_PROXY
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FnGroup}/invocations"
    delete:
      summary: group
      description: deletes a group
      parameters:
        - in: query
          name: uid
          required: true
          schema:
            $ref: "#/components/schemas/uid"
      responses:
        200:
          $ref: "#/components/responses/uid"
        500:
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-amazon-apigateway-request-validator: param
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: AWS_PROXY
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FnGroup}/invocations"
  /user:
    get:
      summary: user
      description: returns list of users
      parameters:
        - in: query
          name: uid
          required: false
          schema:
            $ref: "#/components/schemas/uid"
        - in: query
          name: group_id
          required: false
          schema:
            $ref: "#/components/schemas/uid"
      responses:
        200:
          $ref: "#/components/responses/users"
        500:
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-amazon-apigateway-request-validator: param
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: AWS_PROXY
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FnUser}/invocations"
    post:
      summary: user
      description: create user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user"
      responses:
        200:
          $ref: "#/components/responses/uid"
        500:
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-amazon-apigateway-request-validator: body
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: AWS_PROXY
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FnUser}/invocations"
    put:
      summary: user
      description: updates a user
      parameters:
        - in: query
          name: uid
          required: true
          schema:
            $ref: "#/components/schemas/uid"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user"
      responses:
        200:
          $ref: "#/components/responses/user"
        500:
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-amazon-apigateway-request-validator: both
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: AWS_PROXY
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FnUser}/invocations"
    delete:
      summary: user
      description: deletes a user
      parameters:
        - in: query
          name: uid
          required: true
          schema:
            $ref: "#/components/schemas/uid"
      responses:
        200:
          $ref: "#/components/responses/uid"
        500:
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-amazon-apigateway-request-validator: param
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: AWS_PROXY
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FnUser}/invocations"
  /plan:
    get:
      summary: plan
      description: returns list of plans
      parameters:
        - in: query
          name: uid
          required: false
          schema:
            $ref: "#/components/schemas/uid"
      responses:
        200:
          $ref: "#/components/responses/plans"
        500:
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-amazon-apigateway-request-validator: param
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: AWS_PROXY
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FnPlan}/invocations"
    post:
      summary: plan
      description: creates plan
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/plan"
      responses:
        200:
          $ref: "#/components/responses/uid"
        500:
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-amazon-apigateway-request-validator: body
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: AWS_PROXY
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FnPlan}/invocations"
    put:
      summary: plan
      description: updates a plan
      parameters:
        - in: query
          name: uid
          required: true
          schema:
            $ref: "#/components/schemas/uid"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/plan"
      responses:
        200:
          $ref: "#/components/responses/plan"
        500:
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-amazon-apigateway-request-validator: both
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: AWS_PROXY
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FnPlan}/invocations"
    delete:
      summary: plan
      description: deletes a plan
      parameters:
        - in: query
          name: uid
          required: true
          schema:
            $ref: "#/components/schemas/uid"
      responses:
        200:
          $ref: "#/components/responses/uid"
        500:
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-amazon-apigateway-request-validator: param
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: AWS_PROXY
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FnPlan}/invocations"
  /reading:
    get:
      summary: reading
      description: returns list of readings
      parameters:
        - in: query
          name: uid
          required: false
          schema:
            $ref: "#/components/schemas/uid"
      responses:
        200:
          $ref: "#/components/responses/readings"
        500:
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-amazon-apigateway-request-validator: param
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: AWS_PROXY
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FnReading}/invocations"
    post:
      summary: reading
      description: creates reading
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/reading"
      responses:
        200:
          $ref: "#/components/responses/uid"
        500:
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-amazon-apigateway-request-validator: body
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: AWS_PROXY
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FnReading}/invocations"
    put:
      summary: reading
      description: updates a reading
      parameters:
        - in: query
          name: uid
          required: true
          schema:
            $ref: "#/components/schemas/uid"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/reading"
      responses:
        200:
          $ref: "#/components/responses/reading"
        500:
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-amazon-apigateway-request-validator: both
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: AWS_PROXY
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FnReading}/invocations"
    delete:
      summary: reading
      description: deletes a reading
      parameters:
        - in: query
          name: uid
          required: true
          schema:
            $ref: "#/components/schemas/uid"
      responses:
        200:
          $ref: "#/components/responses/uid"
        500:
          $ref: "#/components/responses/error"
        default:
          $ref: "#/components/responses/error"
      x-amazon-apigateway-request-validator: param
      x-amazon-apigateway-integration:
        httpMethod: POST
        type: AWS_PROXY
        uri:
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${FnReading}/invocations"

x-amazon-apigateway-request-validators:
  both:
    validateRequestBody: true
    validateRequestParameters: true
  body:
    validateRequestBody: true
    validateRequestParameters: false
  param:
    validateRequestBody: false
    validateRequestParameters: true
